# Generated by Django 4.2.1 on 2023-06-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VSgames', '0005_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
        migrations.AddField(
            model_name='post',
            name='vote_sum',
            field=models.IntegerField(default=0),
        ),
    ]
