# Generated by Django 4.2.1 on 2023-06-06 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VSgames', '0006_remove_post_like_post_vote_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='vote_sum',
        ),
    ]
