# Generated by Django 4.2.1 on 2023-06-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VSgames', '0007_remove_post_vote_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vote_sum',
            field=models.IntegerField(default=0),
        ),
    ]
